services:
  discovery:
    build: ./discov-service
    container_name: discovery
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4

  config:
    build: ./config-service
    container_name: config
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery:8761/eureka
    depends_on:
      discovery:
        condition: service_healthy

  customer:
    build: ./customer-service
    container_name: customer
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery:8761/eureka
      - CONFIG_SERVICE_URL=http://config:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config:
        condition: service_healthy

  account:
      build: ./account-service
      container_name: account
      ports:
        - '8082:8082'
      expose:
        - '8082'
      environment:
        - DISCOVERY_SERVICE_URL=http://discovery:8761/eureka
        - CONFIG_SERVICE_URL=http://config:9999
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
        interval: 10s
        retries: 4
      depends_on:
        config:
          condition: service_healthy

  assosiation:
      build: ./assosiation-service
      container_name: assosiation
      ports:
        - '8083:8083'
      expose:
        - '8083'
      environment:
        - DISCOVERY_SERVICE_URL=http://discovery:8761/eureka
        - CONFIG_SERVICE_URL=http://config:9999
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      depends_on:
        customer:
          condition: service_healthy
        account:
          condition: service_healthy

  gateway:
      build: ./gateway-service
      container_name: gateway
      ports:
        - '8888:8888'
      expose:
        - '8888'
      environment:
        - DISCOVERY_SERVICE_URL=http://discovery:8761/eureka
        - CONFIG_SERVICE_URL=http://config:9999
      depends_on:
        assosiation:
          condition: service_healthy

